keys:
  - &users:
    - &tokyo age1hmy7enszx4dmlupgvks5xz66s6n2z0pv53fr9tyc7ah5u345nqmsx0pvm9
  - &hosts:
    - &admin_rafael age1ueegmwzf6khx54sax082r6v5cns3sk35vlg786x5pfku4surfy3sccuw4r
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *tokyo
      - *admin_rafael
